// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4sD7aLmHJ5yjQgE7yvygWzp8zs__9j74',
    appId: '1:839275767953:web:2917d78740e358d1c77730',
    messagingSenderId: '839275767953',
    projectId: 'flutter-login-app-9b559',
    authDomain: 'flutter-login-app-9b559.firebaseapp.com',
    storageBucket: 'flutter-login-app-9b559.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6vV0xtOFblPBXynPNk3R0aloEr5L8J10',
    appId: '1:839275767953:android:c0681ba72212b533c77730',
    messagingSenderId: '839275767953',
    projectId: 'flutter-login-app-9b559',
    storageBucket: 'flutter-login-app-9b559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaw8_rEuxCvqvPwbwhHVtUpEdXHtk1y00',
    appId: '1:839275767953:ios:79dcfb5cac0d3176c77730',
    messagingSenderId: '839275767953',
    projectId: 'flutter-login-app-9b559',
    storageBucket: 'flutter-login-app-9b559.appspot.com',
    iosClientId: '839275767953-h8ieugb0abea9gfoeod0fb3ue0f85jmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthentication',
  );
}
